jobs:
  process-print-responses:
    name: "ProcessPrintResponses"
    cron: "0 */10 * ? * *" # every 10 minutes
  batch-print-requests:
    name: "BatchPrintRequests"
    cron: "0 */10 * ? * *" # every 10 minutes
    daily-limit: 10
